{"timestamp": "2024-10-30 15:50:08", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 15:50:08", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 15:50:10", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 15:50:10", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 15:50:10", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 15:50:11", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 15:50:11", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 15:50:11", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 15:50:11", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 15:50:33", "level": "WARNING", "message": "Not Found: /", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 15:50:33", "level": "WARNING", "message": "\"GET / HTTP/1.1\" 404 3870", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:34", "level": "WARNING", "message": "Not Found: /favicon.ico", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 15:50:34", "level": "WARNING", "message": "\"GET /favicon.ico HTTP/1.1\" 404 3921", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /auth/ HTTP/1.1\" 200 10182", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/css/prettify.css HTTP/1.1\" 200 817", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1\" 200 3426", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1\" 200 121457", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/css/default.css HTTP/1.1\" 200 1152", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/csrf.js HTTP/1.1\" 200 1793", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/ajax-form.js HTTP/1.1\" 200 3796", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1\" 200 39680", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/prettify-min.js HTTP/1.1\" 200 13632", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1\" 200 87533", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1\" 200 59", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/js/default.js HTTP/1.1\" 200 1268", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:38", "level": "INFO", "message": "\"GET /static/rest_framework/img/grid.png HTTP/1.1\" 200 1458", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:50:41", "level": "WARNING", "message": "Unauthorized: /auth/users/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 15:50:41", "level": "WARNING", "message": "\"GET /auth/users/ HTTP/1.1\" 401 15729", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 15:51:04", "level": "ERROR", "message": "Failed to create user", "module": "serializers", "filename": "serializers.py", "funcName": "create", "lineno": 90}
{"timestamp": "2024-10-30 15:51:05", "level": "ERROR", "message": "Internal Server Error: /auth/users/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\viewsets.py\", line 124, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\mixins.py\", line 19, in create\n    self.perform_create(serializer)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\djoser\\views.py\", line 134, in perform_create\n    user = serializer.save(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\serializers.py\", line 208, in save\n    self.instance = self.create(validated_data)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\contextlib.py\", line 81, in inner\n    return func(*args, **kwds)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\users\\serializers.py\", line 76, in create\n    user = User.objects.create(**validated_data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 677, in create\n    obj = self.model(**kwargs)\n          ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\base.py\", line 564, in __init__\n    _setattr(self, prop, value)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\fields\\related_descriptors.py\", line 665, in __set__\n    raise TypeError(\nTypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use roles.set() instead."}
{"timestamp": "2024-10-30 15:51:05", "level": "ERROR", "message": "\"POST /auth/users/ HTTP/1.1\" 500 152560", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 21:49:13", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 21:49:13", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 21:49:15", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 21:49:15", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 21:49:15", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 21:49:16", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 21:49:16", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 21:49:16", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 21:49:16", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 21:53:11", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:01:47", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:02:00", "level": "ERROR", "message": "Internal Server Error: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 194, in post\n    return self.create(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 58, in create\n    startup = get_object_or_404(StartUpProfile, id=self.kwargs[\"startup_id\"])\n                                                   ~~~~~~~~~~~^^^^^^^^^^^^^^\nKeyError: 'startup_id'"}
{"timestamp": "2024-10-30 22:02:00", "level": "ERROR", "message": "\"POST /projects/create HTTP/1.1\" 500 107914", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:02:39", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:02:44", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:02:44", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:02:44", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:02:45", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:02:45", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:02:45", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:02:45", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:02:51", "level": "WARNING", "message": "Not Found: /projects/create/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:02:51", "level": "WARNING", "message": "\"POST /projects/create/ HTTP/1.1\" 404 4936", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:03:15", "level": "ERROR", "message": "Internal Server Error: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 194, in post\n    return self.create(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 58, in create\n    startup = get_object_or_404(StartUpProfile, id=self.kwargs[\"startup\"])\n                                                   ~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'startup'"}
{"timestamp": "2024-10-30 22:03:15", "level": "ERROR", "message": "\"POST /projects/create HTTP/1.1\" 500 107884", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:03:44", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:03:47", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:03:48", "level": "ERROR", "message": "Internal Server Error: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 194, in post\n    return self.create(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 58, in create\n    startup = get_object_or_404(StartUpProfile, id=request[\"startup\"])\n                                                   ~~~~~~~^^^^^^^^^^^\nTypeError: 'Request' object is not subscriptable"}
{"timestamp": "2024-10-30 22:03:48", "level": "ERROR", "message": "\"POST /projects/create HTTP/1.1\" 500 108080", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:05:03", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:05:06", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:05:06", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:05:07", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:05:07", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:05:07", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:05:07", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:05:07", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:05:08", "level": "WARNING", "message": "Not Found: /projects/create/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:05:08", "level": "WARNING", "message": "\"POST /projects/create/ HTTP/1.1\" 404 4936", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:05:27", "level": "WARNING", "message": "Not Found: /projects/ create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:05:27", "level": "WARNING", "message": "\"POST /projects/%20create HTTP/1.1\" 404 4938", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:05:31", "level": "WARNING", "message": "Not Found: /projects/ create/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:05:31", "level": "WARNING", "message": "\"POST /projects/%20create/ HTTP/1.1\" 404 4941", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:05:35", "level": "WARNING", "message": "Not Found: /projects/create/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:05:35", "level": "WARNING", "message": "\"POST /projects/create/ HTTP/1.1\" 404 4936", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:05:50", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\urls.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:05:53", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:05:57", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\urls.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:06:00", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:06:01", "level": "INFO", "message": "\"POST /projects/create HTTP/1.1\" 201 334", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:07:05", "level": "WARNING", "message": "Unauthorized: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:07:05", "level": "WARNING", "message": "\"POST /projects/create HTTP/1.1\" 401 183", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:07:11", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:07:25", "level": "INFO", "message": "\"POST /projects/create HTTP/1.1\" 201 345", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:07:34", "level": "WARNING", "message": "Not Found: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:07:34", "level": "WARNING", "message": "\"POST /projects/create HTTP/1.1\" 404 55", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:07:51", "level": "WARNING", "message": "Unauthorized: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:07:51", "level": "WARNING", "message": "\"POST /projects/create HTTP/1.1\" 401 183", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:08:51", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:09:09", "level": "WARNING", "message": "Forbidden: /projects/create", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:09:09", "level": "WARNING", "message": "\"POST /projects/create HTTP/1.1\" 403 61", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:09:38", "level": "INFO", "message": "\"GET /projects/projects/ HTTP/1.1\" 200 624", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:20:38", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:20:38", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:20:41", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:20:48", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:21:47", "level": "INFO", "message": "\"GET /projects/projects/ HTTP/1.1\" 200 624", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:21:57", "level": "INFO", "message": "\"POST /projects/create HTTP/1.1\" 201 357", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:22:11", "level": "WARNING", "message": "Method Not Allowed: /projects/projects/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:22:11", "level": "WARNING", "message": "\"POST /projects/projects/ HTTP/1.1\" 405 41", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:22:15", "level": "INFO", "message": "\"GET /projects/projects/ HTTP/1.1\" 200 928", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:22:38", "level": "INFO", "message": "\"GET /projects/startup-project/1/ HTTP/1.1\" 200 624", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:22:48", "level": "INFO", "message": "\"GET /projects/startup-project/2/ HTTP/1.1\" 200 355", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:23:37", "level": "ERROR", "message": "Internal Server Error: /projects/project/1/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 230, in put\n    return self.update(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 89, in update\n    project = self.get_object()\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 87, in get_object\n    queryset = self.filter_queryset(self.get_queryset())\n                                    ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 85, in get_queryset\n    return Project.objects.filter(id=self.kwargs[\"project_id\"])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1476, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1494, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1501, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1609, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1641, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1491, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1303, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1768, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: amount, business_plan, created_at, description, duration, investors, media_files, project_id, risk, startup, startup_id, status, subscription, title, updated_at"}
{"timestamp": "2024-10-30 22:23:37", "level": "ERROR", "message": "\"PUT /projects/project/1/update/ HTTP/1.1\" 500 162112", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:23:58", "level": "ERROR", "message": "Internal Server Error: /projects/project/1/update", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\utils\\deprecation.py\", line 131, in __call__\n    response = self.process_response(request, response)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\middleware\\common.py\", line 108, in process_response\n    return self.response_redirect_class(self.get_full_path_with_slash(request))\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\middleware\\common.py\", line 87, in get_full_path_with_slash\n    raise RuntimeError(\nRuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to 127.0.0.1:8000/projects/project/1/update/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings."}
{"timestamp": "2024-10-30 22:23:58", "level": "ERROR", "message": "\"PUT /projects/project/1/update HTTP/1.1\" 500 81032", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:24:44", "level": "ERROR", "message": "Internal Server Error: /projects/project/1/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 230, in put\n    return self.update(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 89, in update\n    project = self.get_object()\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 87, in get_object\n    queryset = self.filter_queryset(self.get_queryset())\n                                    ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 85, in get_queryset\n    return Project.objects.filter(id=self.kwargs[\"project_id\"])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1476, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1494, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1501, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1609, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1641, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1491, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1303, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1768, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: amount, business_plan, created_at, description, duration, investors, media_files, project_id, risk, startup, startup_id, status, subscription, title, updated_at"}
{"timestamp": "2024-10-30 22:24:44", "level": "ERROR", "message": "\"PUT /projects/project/1/update/ HTTP/1.1\" 500 162112", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:28:51", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:28:55", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:28:56", "level": "WARNING", "message": "Unauthorized: /projects/project/1/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:28:56", "level": "WARNING", "message": "\"PUT /projects/project/1/update/ HTTP/1.1\" 401 183", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:29:04", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:29:32", "level": "ERROR", "message": "Internal Server Error: /projects/project/3/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 230, in put\n    return self.update(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 89, in update\n    project = self.get_object()\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 87, in get_object\n    queryset = self.filter_queryset(self.get_queryset())\n                                    ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 85, in get_queryset\n    return Project.objects.filter(id=self.kwargs[\"project_id\"])\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1476, in filter\n    return self._filter_or_exclude(False, args, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1494, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, args, kwargs)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1501, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1609, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1641, in _add_q\n    child_clause, needed_inner = self.build_filter(\n                                 ^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1491, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)\n                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1303, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\db\\models\\sql\\query.py\", line 1768, in names_to_path\n    raise FieldError(\ndjango.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: amount, business_plan, created_at, description, duration, investors, media_files, project_id, risk, startup, startup_id, status, subscription, title, updated_at"}
{"timestamp": "2024-10-30 22:29:32", "level": "ERROR", "message": "\"PUT /projects/project/3/update/ HTTP/1.1\" 500 162112", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:30:33", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:30:37", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:30:38", "level": "ERROR", "message": "Internal Server Error: /projects/project/3/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 230, in put\n    return self.update(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 89, in update\n    project = self.get_object()\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 92, in get_object\n    assert lookup_url_kwarg in self.kwargs, (\nAssertionError: Expected view UpdateProjectView to be called with a URL keyword argument named \"pk\". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly."}
{"timestamp": "2024-10-30 22:30:38", "level": "ERROR", "message": "\"PUT /projects/project/3/update/ HTTP/1.1\" 500 113295", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:31:36", "level": "ERROR", "message": "Internal Server Error: /projects/project/3/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248, "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 65, in _view_wrapper\n    return view_func(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 230, in put\n    return self.update(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\piton\\practice\\UA1244_alpha\\projects\\views.py\", line 89, in update\n    project = self.get_object()\n              ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Polina\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\forum-R3WqLrAe-py3.12\\Lib\\site-packages\\rest_framework\\generics.py\", line 92, in get_object\n    assert lookup_url_kwarg in self.kwargs, (\nAssertionError: Expected view UpdateProjectView to be called with a URL keyword argument named \"pk\". Fix your URL conf, or set the `.lookup_field` attribute on the view correctly."}
{"timestamp": "2024-10-30 22:31:36", "level": "ERROR", "message": "\"PUT /projects/project/3/update/ HTTP/1.1\" 500 113295", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:33:00", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\urls.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:33:04", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:33:08", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:33:12", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:33:13", "level": "WARNING", "message": "Not Found: /projects/project/3/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:33:13", "level": "WARNING", "message": "\"PUT /projects/project/3/update/ HTTP/1.1\" 404 38", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:33:36", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:33:36", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:33:50", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:33:50", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:33:51", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:33:51", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:33:52", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:33:52", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:34:49", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:34:54", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:34:56", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:34:56", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:35:14", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:35:14", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:35:15", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:35:15", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:35:17", "level": "WARNING", "message": "Not Found: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:35:17", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 404 5063", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:36:41", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\urls.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:36:44", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:36:44", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:36:44", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:36:45", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:36:45", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:36:45", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:36:45", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:36:45", "level": "WARNING", "message": "Unauthorized: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:36:45", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 401 183", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:36:52", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:37:04", "level": "WARNING", "message": "Bad Request: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:37:04", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 400 115", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:40:11", "level": "INFO", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 200 190", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:40:50", "level": "INFO", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 200 192", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:41:02", "level": "WARNING", "message": "Bad Request: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:41:02", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 400 37", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:45:35", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\serializers.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:45:39", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:45:39", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:45:39", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:45:40", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:45:40", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:45:40", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:45:40", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:45:52", "level": "WARNING", "message": "Unauthorized: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:45:52", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 401 183", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:45:58", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:46:14", "level": "INFO", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 200 184", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:46:31", "level": "INFO", "message": "\"POST /auth/jwt/create/ HTTP/1.1\" 200 483", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:46:49", "level": "INFO", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 200 62", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
{"timestamp": "2024-10-30 22:47:50", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:47:54", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:48:28", "level": "INFO", "message": "D:\\piton\\practice\\UA1244_alpha\\projects\\views.py changed, reloading.", "module": "autoreload", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266}
{"timestamp": "2024-10-30 22:48:31", "level": "INFO", "message": "Initializing Investors app and importing signals.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 13}
{"timestamp": "2024-10-30 22:48:31", "level": "INFO", "message": "Successfully imported signals for Investors app.", "module": "apps", "filename": "apps.py", "funcName": "ready", "lineno": 16}
{"timestamp": "2024-10-30 22:48:31", "level": "INFO", "message": "Watching for file changes with StatReloader", "module": "autoreload", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668}
{"timestamp": "2024-10-30 22:48:32", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:48:32", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:48:32", "level": "INFO", "message": "Successfully connected to MongoDB at mongodb://localhost:27017", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_client", "lineno": 22}
{"timestamp": "2024-10-30 22:48:32", "level": "INFO", "message": "MongoDBRepository successfully initialized.", "module": "__init__", "filename": "__init__.py", "funcName": "init_mongo_repository", "lineno": 35}
{"timestamp": "2024-10-30 22:48:33", "level": "WARNING", "message": "Forbidden: /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/", "module": "log", "filename": "log.py", "funcName": "log_response", "lineno": 248}
{"timestamp": "2024-10-30 22:48:33", "level": "WARNING", "message": "\"PUT /projects/project/4937b73e-dc4c-47e6-ab0e-518b781de9ce/update/ HTTP/1.1\" 403 62", "module": "basehttp", "filename": "basehttp.py", "funcName": "log_message", "lineno": 213}
